import {concepts} from './concepts';
import {Project} from '../models/project';
export const projects:Project[]=[
{id:'huts-haven',slug:'huts-haven',title:'Huts Haven',category:'Web Design',description:'A nature-inspired website concept blending immersive imagery with a clean, modern experience.',image:'images/huts-haven.webp',technologies:['Figma','HTML/CSS'],concept:true,featured:true},
{id:'comptech',slug:'comptech',title:'CompTech',category:'Web Design',description:'A smart-technology brand site built around bold type and a confident, futuristic tone.',image:'images/comptech.webp',technologies:['Figma','HTML/CSS'],concept:true},
{id:'gps-drone',slug:'gps-drone',title:'GPS Drone',category:'Web Design',description:'A product landing page for a foldable, stable, and smooth-flying drone concept.',image:'images/gps-drone.webp',technologies:['Figma','HTML/CSS'],concept:true},
{id:'notable',slug:'notable',title:'Notable Design Co.',category:'WordPress',description:'An ongoing collaboration spanning Notable’s own website and a range of client projects.',image:'images/notable.webp',technologies:['UI/UX','WordPress'],liveUrl:'https://notabledesign.co/'},
{id:'affinity24',slug:'affinity24',title:'Affinity24',category:'WordPress',description:'WordPress website development completed through Notable Design Co.',image:'images/affinity24.webp',technologies:['WordPress'],liveUrl:'https://affinity24.com/'},
{id:'wine-education-council',slug:'wine-education-council',title:'Wine Education Council',category:'WordPress',description:'WordPress development completed through Notable Design Co.',image:'images/wine-education-council.webp',technologies:['WordPress'],liveUrl:'https://wineeducationcouncil.org/'},
{id:'holy-grail',slug:'holy-grail',title:'Holy Grail Wine Company',category:'WordPress',description:'WordPress website development completed through Notable Design Co.',image:'images/holy-grail.webp',technologies:['WordPress'],liveUrl:'https://holygrailwine.com/'},
{id:'plumbing',slug:'plumbing',title:'Plumbing / Drain Cleaning Website',category:'Web Design',description:'Landing page development completed through Notable Design Co.',image:'images/plumbing.webp',technologies:[]},
{id:'xtremeauto',slug:'xtremeauto',title:'Xtreme Autosports',category:'WordPress',description:'WordPress website development completed through Notable Design Co.',image:'images/xtremeauto.webp',technologies:['WordPress'],liveUrl:'https://xtremeautosportsscv.com/'},
{id:'holy-grail-ui',slug:'holy-grail-ui',title:'Holy Grail Wine Company — UI Design',category:'UI/UX',description:'High-fidelity Figma design for a wine e-commerce site, from shop and wine club to checkout.',image:'images/figma/holy-grail-ui-thumb.webp',fullImage:'images/figma/holy-grail-ui.webp',technologies:['Figma','UI/UX'],overview:['A full high-fidelity design for Holy Grail Wine Company, covering the home page, shop, single product, wine club and member portal, cart, checkout, gift cards, and account pages.','Every key page was designed for both desktop (1440px) and mobile (390px), alongside a style guide, menus, and pop-ups such as the age-gate and wine club sign-up.'],focus:'E-commerce, Desktop & Mobile, Style Guide'},
{id:'affinity24-ui',slug:'affinity24-ui',title:'Affinity 24 — Website Redesign',category:'UI/UX',description:'A Figma redesign of the Affinity 24 website for payment-processing services.',image:'images/figma/affinity24-ui-thumb.webp',fullImage:'images/figma/affinity24-ui.webp',technologies:['Figma','UI/UX'],overview:['A high-fidelity redesign of the Affinity 24 website, built around a clear message for business owners looking to recapture revenue lost to processing fees.','The design covers the home, about, solutions, security, pricing, partnerships, contact, and learning center pages, supported by a dedicated style guide.'],focus:'Redesign, Information Architecture, Style Guide'},
{id:'maari-ma',slug:'maari-ma',title:'Maari Ma Health — Website Design Concepts',category:'UI/UX',description:'Website design concepts for an Aboriginal community health organisation.',image:'images/figma/maari-ma-thumb.webp',fullImage:'images/figma/maari-ma.webp',technologies:['Figma','UI/UX'],overview:['Website design concepts for Maari Ma Health, exploring three colour directions for the home page: Maroon, Saltbush, and Ochre.','Each direction was carried through to a community page and tested with both the organisation’s own imagery and proposed stock imagery, with desktop and mobile layouts.'],focus:'Design Concepts, Colour Direction, Imagery'},
{id:'zenstea',slug:'zenstea',title:'Zenstea — E-commerce Design',category:'UI/UX',description:'A complete Figma e-commerce design for a tea brand, from shop to checkout.',image:'images/figma/zenstea-thumb.webp',fullImage:'images/figma/zenstea.webp',technologies:['Figma','UI/UX'],overview:['A high-fidelity e-commerce design for Zenstea, covering the home page, shop, single product, cart and sidebar cart, checkout, wishlist, gift cards, and account pages.','It also includes content pages for the brand’s story, franchise, herbalism classes, blog, FAQs, and contact, all built from a shared colour and type system.'],focus:'E-commerce, Sitemap & UI Kit, High Fidelity'},
{id:'zens-tea-house',slug:'zens-tea-house',title:'Zen’s Tea House — Corporate Website',category:'UI/UX',description:'A corporate website design for Zen’s Tea House across desktop and mobile.',image:'images/figma/zens-tea-house-thumb.webp',fullImage:'images/figma/zens-tea-house.webp',technologies:['Figma','UI/UX'],overview:['A corporate website design for Zen’s Tea House, separate from its online store, focused on the business behind the brand.','Pages include the home page, about, philanthropy, doctor collaboration, World Tea Expo business, franchise, and contact — each designed for desktop (1440px) and mobile (375px).'],focus:'Corporate Website, Desktop & Mobile'},
{id:'colorsedge',slug:'colorsedge',title:'Colorsedge — Website Design',category:'UI/UX',description:'A bold website design for an automotive refinishing company.',image:'images/figma/colorsedge-thumb.webp',fullImage:'images/figma/colorsedge.webp',technologies:['Figma','UI/UX'],overview:['A high-fidelity website design for Colorsedge, an automotive refinishing company, built around a bold, high-contrast visual style.','The design covers the home page, about, products, locations, contact, and a resource library on paint codes, common paint problems, reducers, training, and refinish terminology.'],focus:'Web Design, Resource Pages, Product Pages'}
];
export const artwork=[...['Aurum','College of Computer Education','Shepherd International','Hutshaven','Brand 05','Brand 06','Brand 07','Brand 08'].map((title,i)=>({title,image:'images/Logo-'+(i+1)+'.webp',kind:'Logo & identity'})),...['aurum','college','shepherd','hutshaven'].map((name,i)=>({title:['Aurum','College of Computer Education','Shepherd International','Hutshaven'][i]+' — concept brand board',image:'images/brand-boards/'+name+'.webp',kind:'Visual identity concept'}))];


for(const concept of concepts){const project=projects.find(p=>p.slug===concept.slug);if(project){project.overview=concept.overview;project.focus=concept.meta.find(m=>m.label==='Focus')?.value;}}

export const graphics=[{title:'STEEZY — Popping: Hits & Musicality',image:'images/graphics/steezy-popping.webp',kind:'Class thumbnail'},{title:'STEEZY — Hip Hop: Foundation Footwork',image:'images/graphics/steezy-hip-hop.webp',kind:'Class thumbnail'},{title:'STEEZY — House: Footwork Fundamentals',image:'images/graphics/steezy-house.webp',kind:'Class thumbnail'},{title:'Ozam Technologies — Website & Logo Offer',image:'images/graphics/ozam-website-promo.webp',kind:'Social media ad'}];
