import {Component,ChangeDetectionStrategy} from '@angular/core';import {RouterLink} from '@angular/router';
interface Role {title:string;company:string;type?:string;period:string;duration?:string;location?:string;summary?:string;points:string[];tools:string[];links?:{label:string;url:string;external?:boolean}[];}
@Component({changeDetection:ChangeDetectionStrategy.OnPush,imports:[RouterLink],template:`<div class="page-heading"><div><div class="eyebrow coral">THE JOURNEY SO FAR</div><h1>Experience, in practice.</h1><p>3+ years designing and building responsive, user-focused websites across brands, industries, and platforms.</p></div></div>
<section class="card content-card"><div class="timeline">@for(r of roles;track r.title+r.company){<article class="timeline-entry"><span class="eyebrow coral">{{r.period}}@if(r.duration){ · {{r.duration}}}</span><h2>{{r.title}}</h2><h3>{{r.company}}</h3>@if(r.type||r.location){<div class="role-meta">@if(r.type){<span>{{r.type}}</span>}@if(r.location){<span>{{r.location}}</span>}</div>}@if(r.summary){<p>{{r.summary}}</p>}@if(r.points.length){<ul>@for(p of r.points;track p){<li>{{p}}</li>}</ul>}@if(r.tools.length){<div class="tags">@for(t of r.tools;track t){<span>{{t}}</span>}</div>}@if(r.links){<div class="actions">@for(l of r.links;track l.label){@if(l.external){<a [href]="l.url" target="_blank" rel="noopener noreferrer" class="button secondary">{{l.label}} ↗</a>}@else{<a [routerLink]="l.url" class="button secondary">{{l.label}} →</a>}}</div>}</article>}</div></section>
<div class="section-heading"><div><div class="eyebrow">FOUNDATION</div><h2>Education</h2></div></div>
<section class="card content-card education-card"><span class="eyebrow coral">2019 – 2024</span><h3>Bachelor of Science in Information Technology (BSIT)</h3><p>Andres Soriano Colleges of Bislig</p></section>`})
export class Experience {roles:Role[]=[
{title:'UI/UX Designer & WordPress Developer',company:'Notable Design Co.',type:'Full-time',period:'Mar 2025 – Sep 2026',duration:'1 yr 7 mos',location:'Remote',summary:'Turning ideas, strategy, and design direction into polished, responsive websites for the agency and client projects across different industries.',points:['Designed and built responsive websites and landing pages for Notable’s own site and its clients.','Developed and customized sites using WordPress, Shopify, Bricks Builder, Elementor, Wix, Squarespace, and Leadpages.','Handled UI/UX implementation, responsive development, Shopify customization, and custom CSS/JavaScript interactions.','Owned website updates, QA, troubleshooting, and ongoing improvements across platforms.'],tools:['Figma','WordPress','Shopify','Bricks Builder','Elementor','Wix','Squarespace','Leadpages','Custom CSS/JS','Cloudways','Cloudflare','Pressable'],links:[{label:'Explore client work',url:'/projects'},{label:'Notable Design Co.',url:'https://notabledesign.co/',external:true}]},
{title:'Freelance UI/UX Designer',company:'Freelance',type:'Self-employed',period:'Feb 2024 – Jan 2025',duration:'1 yr',location:'Remote',summary:'Designed user interfaces and responsive web layouts using Figma, with a focus on usability and user experience.',points:['Created wireframes, prototypes, and high-fidelity designs.','Worked with clients to understand their needs and requirements.'],tools:['Figma','UI/UX Design','Prototyping']},
{title:'IT Support',company:'Awesome CX',period:'2024',points:['Provided technical support to internal staff, troubleshooting hardware, software, and network-related issues.'],tools:['Hardware','Software','Networking']},
{title:'UI Designer',company:'Lines + Pixels',type:'Full-time',period:'Apr 2023 – Jan 2024',duration:'10 mos',location:'Davao City, Philippines · On-site',points:['Designed and developed user-friendly websites with a focus on clear layouts and usability.','Used Figma, Adobe Photoshop, and Illustrator for web and visual design work.'],tools:['Figma','WordPress','Adobe Photoshop','Adobe Illustrator']}];}
