import {Routes} from '@angular/router';import {projects,graphics} from './core/constants/portfolio';
export const routes:Routes=[
{path:'',title:'Overview',data:{description:'Explore CJ Abarca’s creative dashboard: UI/UX, web design, WordPress development, and graphic design.'},loadComponent:()=>import('./pages/overview/overview').then(m=>m.Overview)},
{path:'about',title:'About Me',data:{description:'Meet CJ Abarca, a graphic and web designer turning visual ideas into responsive websites.'},loadComponent:()=>import('./pages/about/about').then(m=>m.About)},
{path:'projects',title:'Selected Projects',data:{description:'Client websites, Figma UI/UX designs, and graphic design — from WordPress and Shopify builds to jerseys, logos, and motion graphics.'},loadComponent:()=>import('./pages/projects/projects').then(m=>m.Projects)},
{path:'wordpress',title:'WordPress',data:{filter:'WordPress',heading:'Built with WordPress.',description:'Live websites built and maintained in WordPress, from wine and non-profit sites to events and local services.'},loadComponent:()=>import('./pages/projects/projects').then(m=>m.Projects)},
{path:'ui-ux',title:'UI/UX Design',data:{filter:'Web & UI/UX',heading:'Clarity in every interaction.',description:'Website designs, Figma UI/UX work, and concepts — from page structures to responsive interfaces.'},loadComponent:()=>import('./pages/projects/projects').then(m=>m.Projects)},
{path:'projects/:slug',title:r=>projects.find(p=>p.slug===r.paramMap.get('slug'))?.title||graphics.find(g=>g.slug===r.paramMap.get('slug'))?.title||'Project not found',loadComponent:()=>import('./pages/project-detail/project-detail').then(m=>m.ProjectDetail)},
{path:'graphic-design',title:'Graphic Design',data:{description:'CJ Abarca’s jerseys, uniforms, thumbnails, posters, logos, and concept brand boards.'},loadComponent:()=>import('./pages/graphic-design/graphic-design').then(m=>m.GraphicDesign)},
{path:'experience',title:'Experience',data:{description:'CJ Abarca’s experience in UI/UX design, WordPress development, and IT support.'},loadComponent:()=>import('./pages/experience/experience').then(m=>m.Experience)},
{path:'skills',title:'Skills & Tools',data:{description:'Explore CJ Abarca’s design, development, CMS, and hosting toolkit.'},loadComponent:()=>import('./pages/skills/skills').then(m=>m.Skills)},
{path:'contact',title:'Contact',data:{description:'Contact CJ Abarca for web design, UI/UX, WordPress development, and graphic design opportunities.'},loadComponent:()=>import('./pages/contact/contact').then(m=>m.Contact)},
{path:'**',title:'Page not found',loadComponent:()=>import('./pages/not-found/not-found').then(m=>m.NotFound)}];
