import {Routes} from '@angular/router';import {projects,artwork} from './core/constants/portfolio';
export const routes:Routes=[
{path:'',title:'Overview',data:{description:'Explore CJ Abarca’s creative dashboard: UI/UX, web design, WordPress development, and graphic design.'},loadComponent:()=>import('./pages/overview/overview').then(m=>m.Overview)},
{path:'about',title:'About Me',data:{description:'Meet CJ Abarca, a graphic and web designer turning visual ideas into responsive websites.'},loadComponent:()=>import('./pages/about/about').then(m=>m.About)},
{path:'projects',title:'Selected Projects',data:{description:'Explore CJ Abarca’s concept websites and client projects, from Huts Haven to Notable Design Co.'},loadComponent:()=>import('./pages/projects/projects').then(m=>m.Projects)},
{path:'wordpress',title:'WordPress',data:{filter:'WordPress',heading:'Built with WordPress.',description:'Selected WordPress work, including Holy Grail Wine Company, Xtreme Autosports, Affinity24, and Wine Education Council.'},loadComponent:()=>import('./pages/projects/projects').then(m=>m.Projects)},
{path:'ui-ux',title:'UI/UX Design',data:{filter:'UI/UX',heading:'Clarity in every interaction.',description:'Figma website concepts and UI/UX implementation, from page structures to responsive interfaces.'},loadComponent:()=>import('./pages/projects/projects').then(m=>m.Projects)},
{path:'projects/:slug',title:r=>projects.find(p=>p.slug===r.paramMap.get('slug'))?.title||artwork[Number(r.paramMap.get('slug')?.replace('brand-',''))-1]?.title||'Project not found',loadComponent:()=>import('./pages/project-detail/project-detail').then(m=>m.ProjectDetail)},
{path:'graphic-design',title:'Graphic Design',data:{description:'CJ Abarca’s thumbnails, social media graphics, logo artwork, and concept brand boards.'},loadComponent:()=>import('./pages/graphic-design/graphic-design').then(m=>m.GraphicDesign)},
{path:'experience',title:'Experience',data:{description:'CJ Abarca’s ongoing UI/UX and WordPress development collaboration with Notable Design Co.'},loadComponent:()=>import('./pages/experience/experience').then(m=>m.Experience)},
{path:'skills',title:'Skills & Tools',data:{description:'Explore CJ Abarca’s design, development, CMS, and hosting toolkit.'},loadComponent:()=>import('./pages/skills/skills').then(m=>m.Skills)},
{path:'contact',title:'Contact',data:{description:'Contact CJ Abarca for web design, UI/UX, WordPress development, and graphic design opportunities.'},loadComponent:()=>import('./pages/contact/contact').then(m=>m.Contact)},
{path:'**',title:'Page not found',loadComponent:()=>import('./pages/not-found/not-found').then(m=>m.NotFound)}];
