import {imageDimensions} from '../../core/constants/image-dimensions';
import {Component,signal,computed,viewChild,ElementRef,ChangeDetectionStrategy} from '@angular/core';import {graphics,graphicCategories} from '../../core/constants/portfolio';import {ArtLightbox} from '../../shared/components/art-lightbox';import {Icon} from '../../shared/components/icon';
@Component({changeDetection:ChangeDetectionStrategy.OnPush,imports:[ArtLightbox,Icon],template:`<div class="page-heading"><div><div class="eyebrow coral">GRAPHIC DESIGN / VISUAL IDENTITY</div><h1>A different kind of expression.</h1><p>Jerseys, uniforms, thumbnails, posters, motion graphics, logos, and brand boards. Select a piece for a closer look.</p></div></div>
<div class="filters-anchor" #anchor></div><div class="filters filters--sticky" aria-label="Filter graphics by category"><button [attr.aria-pressed]="filter()==='All'" (click)="choose('All')">All <span class="filter-count">{{all.length}}</span></button>@for(c of categories;track c.name){<button [attr.aria-pressed]="filter()===c.name" (click)="choose(c.name)">{{c.name}} <span class="filter-count">{{count(c.name)}}</span></button>}</div>
@for(group of groups();track group.name){<section class="art-section" [attr.aria-labelledby]="'cat-'+$index"><div class="art-section-heading"><h2 [id]="'cat-'+$index">{{group.name}}</h2><p>{{group.description}}</p></div><div class="art-grid">@for(a of group.items;track a.slug){<button class="art-tile" (click)="lightbox().open(a.slug)" [attr.aria-label]="'Open '+a.title"><span class="art-frame"><img class="cover-backdrop" [src]="'/'+a.image" alt="" aria-hidden="true" loading="lazy"/><img class="art-image" [src]="'/'+a.image" [alt]="a.title" loading="lazy" [width]="dimensions[a.image].width" [height]="dimensions[a.image].height"/></span>@if(a.video){<span class="play-badge" aria-hidden="true"><app-icon name="play"/></span>}<span class="art-caption">{{a.title}}</span></button>}</div></section>}
<p class="note">Untitled logos retain their original numbered labels.</p>
<app-art-lightbox [items]="visible()"/>`})
export class GraphicDesign {dimensions=imageDimensions;all=graphics;categories=graphicCategories;filter=signal<string>('All');
groups=computed(()=>this.categories.filter(c=>this.filter()==='All'||c.name===this.filter()).map(c=>({...c,items:this.all.filter(g=>g.category===c.name)})).filter(c=>c.items.length));
visible=computed(()=>this.groups().flatMap(g=>g.items));
lightbox=viewChild.required(ArtLightbox);anchor=viewChild.required<ElementRef<HTMLElement>>('anchor');
choose(c:string){this.filter.set(c);const el=this.anchor().nativeElement;if(el.getBoundingClientRect().top<0)el.scrollIntoView({behavior:'smooth'});}
count(name:string){return this.all.filter(g=>g.category===name).length;}}
